[package]
name = "middleware"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
tower = "0.4"
axum = "0.7"
axum-jwks = { path = "../../axum-jwks" }
axum-extra = { version = "0.9.0", features = ["typed-header"] }
